### ISSUE TITLE
Missing CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by GodfreyOfBouillon** [hudec117/Mpv.WPF#1]
Refer here: https://github.com/folkswhocode/awesome-diversity/blob/master/CODE_OF_CONDUCT.md
This project will quickly descend into a cesspool of discrimination against age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation if such a document is not included.

**Comment by hudec117** [comment]
CODE_OF_CONDUCT added, will be referenced to by CONTRIBUTING.md when written.
