### ISSUE TITLE
Suggestion to enable instantiating player from XAML

### ISSUE THREAD

**Issue by milleniumbug** [hudec117/Mpv.WPF#2]
> The MpvPlayer cannot be declared in XAML since it needs to be instantiated with the path to the libmpv DLL.

I have several suggestions:
- set the path through a `DependencyProperty` which would lazily initialize the control with the given path.
- or, do something sensible on default construction, like search through `%PATH%` or the directory executable is located for the dll.

**Comment by hudec117** [comment]
I tried to implement your lazy initialisation suggestion and I came across a few annoying problems. (mainly with user control initialisation)

On the other hand, I have found a solution which might be suitable.

I have added a LibMpvPath dependency property into the MpvPlayer class. This property is set-able from XAML but is optional. It will resort to a default value of: "lib\\\\mpv-1.dll".

So this will attempt to load libmpv located at "lib\\mpv-1.dll"
```xaml
<mpvWPF:MpvPlayer x:Name="player" />
```
and this will attempt to load libmpv from wherever specified:
```xaml
<mpvWPF:MpvPlayer
    x:Name="player"
    LibMpvPath="custom\\folder\\structure\\mpv-1.dll" />
```

@milleniumbug what do you think?

**Comment by milleniumbug** [comment]
It looks like WPF is calling `BeginInit()` and `EndInit()` which we could override and provide our own implementation in addition to what WPF is doing. I think this is what we need, but I need to look into this more closely. From my personal experiments it looks like these are called twice, once on `InitializeComponent()` and second time when XAML is setting properties.

**Comment by hudec117** [comment]
Good idea. You're right about `BeginInit()` and `EndInit()` being called twice. As you pointed out, they are called twice. From my experiment, the actual value for `LibMpvPath` becomes available on the _second_ call of `EndInit()`.

I compared the affects of initialiastion in the second `EndInit()` and on the `Loaded` event and they are very similar.

**Comment by hudec117** [comment]
Closed as WPF dependencies have been removed.
