### ISSUE TITLE
Change Play Speed

### ISSUE THREAD

**Issue by mysteryx93** [hudec117/Mpv.WPF#4]
Is there a way to change the play speed using Mpv? I see it in the list of keyboard shotcuts so the feature is there so there has to be a way.
https://www.cheatography.com/someone/cheat-sheets/mpv-media-player/

**Comment by hudec117** [comment]
Hiya @mysteryx93, there sure is a way! I'll release 0.8.0 to include this and an updated Mpv.NET reference. ;)
