### ISSUE TITLE
Why Mpv.WPF ?

### ISSUE THREAD

**Issue by mysteryx93** [hudec117/Mpv.WPF#5]
I'm a bit confused between Mpv.NET and Mpv.WPF ... as this really contains no WPF interface at all.

Truth is, you can host the control within a WindowsFormsHost, and don't need to create the handle manually.

```
<WindowsFormsHost Margin="0,0,0,28">
    <wf:Panel x:Name="Host"></wf:Panel>
</WindowsFormsHost>
```

Then you simply pass Host.Handle and the DLL path in the constructor. I've already changed the code in such a way and it's working. Would you like me to submit the changes for merge?

Advantages:
- Class library has no reference to WPF and can work on any UI
- Mpv.NET and Mpv.WPF could be merged into the same project (highly recommended)

I've also added code to make DllPath optional and first try specified path, then try "mpv-1.dll", and finally try "lib\\mpv-1.dll".

Disadvantages:
- The handles only get created in Windows.Load and you can't initialize or use the player before that, but that's a minor issue easy to work-around.

If you want, I can submit the work I've done so far, and this would be left to do:
- Merge Mpv.NET and Mpv.WPF together
- Move them into a .NET Standard project so it works on any platform, I don't think it uses anything not supported by .NET Standard.
- Do a bit of refactoring to smooth things out.

**Comment by hudec117** [comment]
Interesting proposition.

You say that the projects could be merged into a single .NET Standard project, how would this work with the WindowsFormsHost?

And if we did merge the projects, how would it interface with WPF/WinForms?

If you could push the changes to your fork I'll hapilly give it a look.

**Comment by mysteryx93** [comment]
Sent.

**Comment by hudec117** [comment]
Coo, I will start merging the projects. Also, I will have to include some documentation for WPF/WinForms usage.

**Comment by mysteryx93** [comment]
WinForms usage will be very easy, as every control already has a HWND -- just pass the HWND of any control.

**Comment by hudec117** [comment]
Is there a reason for the panel inside the WindowsFormsHost? I checked and the WindowsFormHost has a handle too, maybe we could use that instead?

**Comment by mysteryx93** [comment]
I tried and it didn't work for me, but it worked with a panel.

**Comment by hudec117** [comment]
Yeah sorry, spoke too soon.

**Comment by hudec117** [comment]
I've deprecated this package and most of the changes have been pushed to the dev branch on the Mpv.NET repository.
