### ISSUE TITLE
Toggle Fullscreen

### ISSUE THREAD

**Issue by mysteryx93** [hudec117/Mpv.WPF#7]
This would be another very useful feature: Toggle Fullscreen. Will it be implemented?

In the meantime, perhaps I can send specific commands in plain text to the player, since it exposes both a plain-text interface and a wrapper around it?

Also, if I want to loop, is there a way for MPV to not unload the file at the end?

**Comment by hudec117** [comment]
MPV does have this feature but I haven't tried to implement it.

There is! Have a look at the KeepOpen property on the player.

**Comment by mysteryx93** [comment]
Ah good thanks. Problem is, if KeepOpen = true, then MpvOnEndFile never triggers and I can't detect the end of file to loop.

I'm developing a really great UI for the player. Will have to wait for an updated version of MPV.NET with a few fixes to release it, unless I want to copy/deploy my own copy/version of the code. The good thing about my UI is that you can easily switch the player and keep the same UI features. It even adds keyboard shortcuts.

**Comment by hudec117** [comment]
Looks like there is a "loop" property in mpv which can be set. I'll implement it.

Nice 👍

**Comment by hudec117** [comment]
This option/property should be doing the trick: https://mpv.io/manual/master/#options-fullscreen

But whenever I set it, nothing happens. The debug log shows:

```
[vo/gpu] Resize: 684x431
[vo/gpu] Window size: 684x431
[vo/gpu] Video source: 1280x720 (1:1)
[vo/gpu] Video display: (0, 0) 1280x720 -> (0, 23) 684x384
[vo/gpu] Video scale: 0.534375/0.533333
[vo/gpu] OSD borders: l=0 t=23 r=0 b=24
[vo/gpu] Video borders: l=0 t=23 r=0 b=24
[vo/gpu] Reported display depth: 8
[cplayer] Set property: fullscreen="yes" -> 1
```

Which means that the property is being set but I suspect that mpv is resizing to the maximum of the host control. The only workaround that I see is creating a custom window and setting it as the host and then somehow fullscreening it.

**Comment by hudec117** [comment]
Also, I pushed the Loop change to dev.

**Comment by mysteryx93** [comment]
Great thx. I managed to get full-screen to work. I need to put it into a full-screen window anyway if I want to be able to bind keyboard shortcuts and display controls on top. Got it all working, including displaying the bar in full-screen when hovering at the bottom. Check it out https://github.com/mysteryx93/MediaPlayerUI.NET

**Comment by hudec117** [comment]
Closed as it doesn't seem possible to fullscreen an embedded mpv instance. Either use @mysteryx93's MediaPlayerUI.NET or embed mpv in a separate window and fullscreen it.
